### ISSUE TITLE
Add more error pages

### ISSUE THREAD

**Issue by Touchcreator** [1hostjs/errors#8]
we need to take over the other hosting things or whatever, so add more pages to be epic 👍

**Comment by wgyt** [comment]
> we need to take over the other hosting things or whatever, so add more pages to be epic 👍

the error pages are able to be used by any module
the error codes and names are able to be changed because this uses ejs

**Comment by wgyt** [comment]
by default 1host only uses this for the 501 site doesn't exist error page, but other modules can use this as an error page

**Comment by wgyt** [comment]
if you want different styles that would be a nice idea

**Comment by Touchcreator** [comment]
> if you want different styles that would be a nice idea

thats what i mean

**Comment by wgyt** [comment]
this would make the file size bigger, I guess we could do that

**Comment by wgyt** [comment]
I think I found a way to do this:
because 2.1.0 added config, the user can use a custom template
```js
// example config
{ "custom":true,"templatepath":"./idk.ejs"}
```
